### ISSUE TITLE
Update plugins.octoprint.org ?

### ISSUE THREAD

**Issue by coliss86** [danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer#13]
Hi, 

thanks for your work !

The [wiring diagram](https://plugins.octoprint.org/plugins/shutdownbuttonledbuzzer/) on [plugins.octoprint.org](https://plugins.octoprint.org) is outdated but I see that on this repo, it is correct, can you please update it ?

Thanks !

**Comment by danieleborgo** [comment]
Hi,
you're right. The difference is just the representation I changed after [this discussion](https://github.com/danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer/discussions/7).

I plan to add a new feature (the other issue) and then I'm going to update it on the official repository.
Thank you
