### ISSUE TITLE
Buzzer not buzzing, only low volume "ticking"

### ISSUE THREAD

**Issue by unisev** [danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer#9]
Hello,

I've tried 2 different buzzer (one little from PC motherboard and one larger from Arduino kit), they are both well working well with an Arduino test sketch but no sound with ShutdownButtonLEDBuzzer
 plugin on PI 3 B.

I think the wiring is okay because when it should buzz, I can hear a small "ticking" from the buzzer.

Is there a specific model to buy ?

**Comment by danieleborgo** [comment]
Hi,
with these two buzzer are you using Arduino Tone or something similar? If yes, it is because you're using passive buzzer instead of active ones, since the plugin wants these lasts.
I'm planning to extend the plugin to support also passive buzzers, but I need to find one before.

**Comment by unisev** [comment]
Yes my buzzers are passive.

I'll wait for the next version of your wonderfull plugin that simplify a lot thoses little octopi hardware upgrade.

**Comment by danieleborgo** [comment]
I implemented passive buzzers.
I suggest to uninstall the plugin and install it again. Then, if you go in its settings page, you can set your buzzer as passive and define which note it has to play.

**Comment by unisev** [comment]
Hello,

Yes it is working, the sound id not very regular, but it is okay !

Thank you very much !
